import sys
from cx_Freeze import setup, Executable

paths = sys.path.copy()
paths.append("src")

# Dependencies are automatically detected, but it might need fine tuning.
build_exe_options = {
    # "replace_paths": ["*=carrot"],
    "path": paths,
    "packages": ["carrot", "carrot.model", "carrot.view", "carrot.controller"],
    "excludes": [
        "PIL.GifImagePlugin",
        "PIL.FpxImagePlugin",
        "PIL.ImageFilter",
        "PIL.ImageQt",
        "PIL.ImageShow",
        "PIL.MicImagePlugin",
        "PIL.PyAccess",
        "bdb",
        "cffi",
        "copy",
        "doctest",
        "email",
        "email._header_value_parser",
        "email._policybase",
        "email.feedparser",
        "email.generator",
        "email.headerregistry",
        "email.headerregistry",
        "email.message",
        "email.parser",
        "email.policy",
        "email.utils",
        "importlib._bootstrap",
        "importlib._bootstrap_external",
        "importlib.abc",
        "importlib.metadata",
        "importlib.resources",
        "importlib.util",
        "multiprocessing.resource_tracker",
        "multiprocessing.shared_memory",
        "multiprocessing.util",
        "packaging._manylinux",
        "pathlib",
        "pdb",
        "pkg_resources",
        "py_compile",
        "pyvips.vimage",
        "rlcompleter",
        "setuptools._distutils.py38compat",
        "setuptools._vendor.packaging._manylinux",
        "tracemalloc",
        "unittest",
        "urllib",
        "warnings",
        "wheel.vendored.packaging._manylinux",
        "zipfile",
        "zipimport",
    ],
    "includes": ["pyvips"],
    "include_files": [
        ("lib64/libvips/libglib-2.0-0.dll", "lib/libglib-2.0-0.dll"),
        ("lib64/libvips/libgobject-2.0-0.dll", "lib/libgobject-2.0-0.dll"),
        ("lib64/libvips/libvips-42.dll", "lib/libvips-42.dll"),
        ("lib64/libvips/libvips-cpp-42.dll", "lib/libvips-cpp-42.dll"),
        ("res/ico/app.ico", "_internal/res/ico/app.ico"),
        ("res/ico/file_exit.png", "_internal/res/ico/file_exit.png"),
        ("res/ico/file_exit_24.png", "_internal/res/ico/file_exit_24.png"),
        ("res/ico/file_export.png", "_internal/res/ico/file_export.png"),
        ("res/ico/file_export_24.png", "_internal/res/ico/file_export_24.png"),
        ("res/ico/file_new.png", "_internal/res/ico/file_new.png"),
        ("res/ico/file_new_24.png", "_internal/res/ico/file_new_24.png"),
        ("res/ico/file_open.png", "_internal/res/ico/file_open.png"),
        ("res/ico/file_open_24.png", "_internal/res/ico/file_open_24.png"),
        ("res/ico/file_save.png", "_internal/res/ico/file_save.png"),
        ("res/ico/file_saveas.png", "_internal/res/ico/file_saveas.png"),
        ("res/ico/file_saveas_24.png", "_internal/res/ico/file_saveas_24.png"),
        ("res/ico/file_save_24.png", "_internal/res/ico/file_save_24.png"),
        ("res/ico/go_back.png", "_internal/res/ico/go_back.png"),
        ("res/ico/go_back_16.png", "_internal/res/ico/go_back_16.png"),
        ("res/ico/go_back_24.png", "_internal/res/ico/go_back_24.png"),
        ("res/ico/go_forward.png", "_internal/res/ico/go_forward.png"),
        ("res/ico/go_forward_24.png", "_internal/res/ico/go_forward_24.png"),
        ("res/ico/help_about_24.png", "_internal/res/ico/help_about_24.png"),
        ("res/ico/help_about_32.png", "_internal/res/ico/help_about_32.png"),
        ("res/ico/help_view.png", "_internal/res/ico/help_view.png"),
        ("res/ico/help_view_24.png", "_internal/res/ico/help_view_24.png"),
        ("res/ico/selection_contract.png", "_internal/res/ico/selection_contract.png"),
        ("res/ico/selection_contract_24.png", "_internal/res/ico/selection_contract_24.png"),
        ("res/ico/selection_expand.png", "_internal/res/ico/selection_expand.png"),
        ("res/ico/selection_expand_24.png", "_internal/res/ico/selection_expand_24.png"),
        ("res/ico/selection_mark.png", "_internal/res/ico/selection_mark.png"),
        ("res/ico/selection_mark_24.png", "_internal/res/ico/selection_mark_24.png"),
        ("0.jpg", "_internal/0.jpg"),
        ("1.jpg", "_internal/1.jpg"),
        ("2.jpg", "_internal/2.jpg"),
        ("3.jpg", "_internal/3.jpg"),
        ("4.jpg", "_internal/4.jpg"),
        ("5.jpg", "_internal/5.jpg"),
        ("6.jpg", "_internal/6.jpg"),
        ("7.jpg", "_internal/7.jpg"),
        ("8.jpg", "_internal/8.jpg"),
    ],
    # "bin_path_includes": ["lib64/libvips"],
    # "bin_includes": [
        # "libglib",
        # "libgobject",
        # "libvips",
        # "libvips-cpp",
    # ],
    # "silent": True,
    "silent_level": 1, # 0=Info, 1=Warning, 2=Error, 3=Nothing
}

# base="Win32GUI" should be used only for Windows GUI app
base = "Win32GUI" if sys.platform == "win32" else None

setup(
    name="Carrot 2025",
    version="0.0.1.0",
    description="Crop, Resize and Rotate",
    options={"build_exe": build_exe_options},
    executables=[
        Executable(
            "src/carrot/app.py",
            base=base,
            target_name="carrot",
            icon="res/ico/app.ico",
            copyright="© 2025 gyk4j. All rights reserved.",
            trademarks="carrot is a trademark of gyk4j",
        )
    ],
)
